import { Car } from "../models/carModel.js";
import { User } from "../models/UserModel.js";

// Manage Users:

//Get all users
export const getAllUsers = async (req, res) => {
  try {
    const users = await User.find().select("-password");
    res.json(users);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Update a user role
export const changeUserRole = async (req, res) => {
  try {
    const { email, newRole } = req.body; //admin will give new role in form/button
    const user = await User.findOne({ email });

    if (!user) {
      res.status(401).json({ message: "User does not exist" });
    }

    user.role = newRole;
    await user.save();
    res.status(200).json({ message: "User role has changed successfully" });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// deleteUser(userId): Remove a user from the platform.
export const deleteUser = async (req, res) => {
  try {
    const user_id = req.params.id;

    const user = await User.findById(user_id);
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    await User.findByIdAndDelete(user_id);
    res.status(200).json({ message: "User has deleted successfully" });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Manage Cars:
// getAllCars(): Fetch details of all cars listed on the platform.
export const getAllCars = async (req, res) => {
  try {
    const cars = await Car.find();
    res.status(200).json(cars);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
}


// Add a new car to the platform
export const addCar = async (req, res) => {
  try {
    const {
      brand,
      model,
      year,
      registrationNumber,
      type,
      color,
      rentalPricePerDay,
      fuelType,
      transmission,
      seats,
      status,
      mileage,
      description,
      images,
      currentLocation,
    } = req.body;

    // You might also extract the user ID from req.user if you have user authentication.
    const ownerId = req.user._id;

    const isCarExist = await Car.findOne({ registrationNumber });
    if (isCarExist) {
      return res.status(400).json({ message: 'Car with this registration number already exists' });
    }

    const newCar = new Car({
      brand,
      model,
      year,
      registrationNumber,
      type,
      color,
      rentalPricePerDay,
      fuelType,
      transmission,
      seats,
      status,
      mileage,
      description,
      images,
      currentLocation,
      ownerId, // owner is the mediator or admin adding the car
    });


    await newCar.save();

  
    return res.status(201).json({
      message: 'Car added successfully',
      car: newCar,
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({ message: 'Failed to add car' });
  }
};


// deleteCar(carId): Remove a car from the platform.
export const deleteCar = async (req, res) => {
  try {
    const car_id = req.params.id;

    const car = await Car.findById(car_id);
    if (!car) {
      return res.status(404).json({ message: "car not found" });
    }

    await User.findByIdAndDelete(car_id);
    res.status(200).json({ message: "Car has deleted successfully" });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// View Reports:
// viewBookingReport(): View statistics and reports related to car bookings.
// viewRevenue(): View total revenue generated by the platform

// Manage Website Settings:
// updateSettings(): Modify website-wide settings (e.g., rental policies, payment settings).